name: Login

on:
  workflow_call:
  
jobs:
  install_az_cli:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
   
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
