name: AzureLog

on: 
 workflow_call:

jobs:

 azlogin:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
